FROM eclipse-temurin:25.0.2_10-jre-noble
WORKDIR /app
RUN groupadd --system appgroup && useradd --system --gid appgroup --create-home appuser
COPY app.jar app.jar
RUN chown -R appuser:appgroup /app
EXPOSE 8080
ENV JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
USER appuser
CMD ["java", "-jar", "app.jar"]
