spring:
  application:
    name: job-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://localhost:5432/freelancedb-jobs}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASS:postgres}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: jackson
  mongodb:
    uri: ${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/freelancemongo}}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${REDIS_HOST:localhost}}
      port: ${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}
      password: ${SPRING_DATA_REDIS_PASSWORD:${REDIS_PASSWORD:redispass}}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:${ELASTICSEARCH_URIS:http://localhost:9200}}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

job-service:
  rabbitmq:
    trusted-event-package: com.team01.freelance.contracts.events
          
server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: job-service
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

contract:
  service:
    base-url: ${CONTRACT_SERVICE_BASE_URL:http://contract-service:8080}
proposal:
  service:
    base-url: ${PROPOSAL_SERVICE_BASE_URL:http://proposal-service:8080}

feign:
  user-service:
    url: http://user-service:8080
  job-service:
    url: http://job-service:8080
  proposal-service:
    url: http://proposal-service:8080
  contract-service:
    url: http://contract-service:8080
  wallet-service:
    url: http://wallet-service:8080
