CREATE TABLE IF NOT EXISTS proposal_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    milestone_order INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount DOUBLE NOT NULL,
    status VARCHAR(32) NOT NULL,
    metadata JSON
);
