-- Shared contracts table (owned by contract-service in production; created here for user-service tests).
CREATE TABLE IF NOT EXISTS contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    freelancer_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    proposal_id BIGINT NOT NULL,
    agreed_amount DOUBLE NOT NULL,
    status VARCHAR(32) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP,
    metadata JSON,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    freelancer_id BIGINT NOT NULL,
    cover_letter VARCHAR(255) NOT NULL,
    bid_amount DOUBLE NOT NULL,
    estimated_days INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    metadata JSON,
    submitted_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP
);
