apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: freelance
spec:
  serviceName: neo4j-headless
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: neo4j/neo4jpass
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
            - name: NEO4J_server_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_server_memory_heap_max__size
              value: "512m"
            - name: NEO4J_server_memory_pagecache_size
              value: "256m"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "768Mi"
              cpu: "100m"
            limits:
              memory: "1280Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 2Gi
